version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: drf-dev-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - djangodb:/var/lib/postgresql/data
volumes:
  djangodb: